name: Breast
main: cn.winfxk.breast.Breast
api:
- 1.0.0
version: 1.0-Gamma
website: http://Winfxk.EpicFX.cn
description: 物品编辑器
author: Winfxk
loadbefore:
- EconomyAPI
permissions:
   Breast.Command.main:
      description: Breast-Main
      default: true